[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
fastReruns = true

[client]
showErrorDetails = false

[logger]
level = "info"