[general]
NEWS_API_KEY = "e9a3b31b8d6f4902920b82de96c9fc08"
GOOGLE_FACT_CHECK_API_KEY = "AIzaSyDrfYK2OjlZ8EsYQ4zP2gYaUcoLFWN3l4g"
GUARDIAN_API_KEY = "f1165623-37ca-4552-8a58-6715a8db036b"

[slack]
SLACK_TOKEN = "xoxb-8125483875847-8162821572080-GYrEkLfKn9VIPcKlMCeaJ0rv"
SLACK_CHANNEL = "#misinformation-detector"
WEBHOOK_URL = "https://webhook.site/bb193e43-8a7f-4dc6-b01c-bd75310a9883"

[twitter]
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAACxmxgEAAAAAEbKpsRv5vYtNXcgrYW98R6IQNfk%3DeEgireTN4fakMRiTmsci5gEQVXHxJ7r4zULnFGaImjjjuaw3MH"
TWITTER_API_KEY = "SMZFAp006j0ygi9t1z5a1X0D7"
TWITTER_API_SECRET = "CCTSdIbEekcHWIVe8lOKaZB7yf72B87ax4YA9cd9p3b7PpeuGC"
TWITTER_ACCESS_TOKEN = "808496445103964160-X23fadspvIzgj0ZfdZHLBi8LmCskBA7"
TWITTER_ACCESS_SECRET = "J6FZzaijA9Ix3JrpxRhzjBjidQkvIbMyb1jToQ8v1BAXU"

[reddit]
REDDIT_CLIENT_ID = "Z1eebKCpcVTEho99KlB6ZQ"
REDDIT_CLIENT_SECRET = "17xiY0BO60GLloD9KVtgYT7BjJQo4A"

[facebook]
FACEBOOK_ACCESS_TOKEN = "EAB2MLuO8BSIBO2VsbbLgcMmQevNP7TM3RaqX8bO08n3j8KGDTOeURafEjZAxSTLCQWwwch7EIr3ZBZCMzQRQSDAugepZCxG16APnVVvIVrJiMZB83K3vuLAaZBZBi1x0Cs57W7XxaakECnvZA0NHr14fiZCXWfK45XSI8eQ4hKW1saJwITNIN9OMCM1itI3jXqbaZBu9FPiNlWI0ESHmoeLAcZD"

[wandb]
WANDB_API_KEY = "568bae06fd1dc0204ceba6f5e67833cbd39d26b1"

[transformers]
TRANSFORMERS_CACHE = ".cache/huggingface"
TORCH_HOME = ".cache/torch"
USE_CPU = true